export const palette = {
  orangeLight: "#FFB051",
  transparent: "transparent",
  white: "#fff",
  mistyWhite: "#f2f2f2",
  black: "black",
  darkGreen: "#2DC231",
  darkGreenLowOpacity: "rgba(45, 194, 49, 0.18)",
  middleGreen: "#35c731",
  middleLightGreen: "#15B400",
  lightGreen: "#68E631",
  lightGreenLowOpacity: "rgba(104, 230, 49, 0.18)",
  darkOrange: "#FB9319",
  lightOrange: "#FFC300",
  veryDarkGray: "#707070",
  transparentVeryDarkGray: "rgba(233, 233, 233, 0.75)",
  darkGray: "#919191",
  middleGray: "#C9C9CB",
  middleLightGray: "#F4F4F4",
  middleDarkGray: "#B2B2B2",
  ashGray: "rgba(244, 244, 244, 0.4)",
  lightGray: "rgba(244, 244, 244, 0.6)",
  courtGray: "#efefef",
  backgroundGray: "#F8F8F8",
  juicyRed: "#ff1212",
  transparentBlack: "rgba(0, 0, 0, 0.7)",
  veryLightGreen: "#8DFB19",
  yellow: "#FBC619",
  mistyGray: "#F7F7F7",
  brightGreen: "#54F73F",
  shadyOrange: "#FBC62D",
  grapefruitOrange: "#FB7325",
  transparentGray: "rgba(125, 125, 125, 0.25)",
  buttonsGray: "#bfbfbf",
};

export const colors = {
  primary: palette.orangeLight,
  mainBg: palette.white,
  transparent: palette.transparent,
  textPrimary: palette.black,
  textSecondary: palette.white,
  greenSliderDot: palette.darkGreen,
  sliderDots: palette.middleGray,
  textTertiary: palette.middleGray,
  greenText: palette.middleGreen,
  darkgrayText: palette.veryDarkGray,
  gradientDarkGreen: palette.darkGreen,
  gradientDarkGreenLowOpacity: palette.darkGreenLowOpacity,
  gradientLightGreen: palette.lightGreen,
  gradientLightGreenLowOpacity: palette.lightGreenLowOpacity,
  gradientDarkOrange: palette.darkOrange,
  gradientLightOrange: palette.lightOrange,
  darkGrayBackground: palette.middleGray,
  middleGrayBackground: palette.middleLightGray,
  lightGrayBackground: palette.lightGray,
  darkGrayFont: palette.darkGray,
  darkGrayShadow: palette.darkGray,
  backgroundTransparent: palette.transparent,
  redBackground: palette.juicyRed,
  grayCourtBackground: palette.courtGray,
  transparentBlackBackground: palette.transparentBlack,
  percentFontGreen: palette.middleLightGreen,
  greenUnderline: palette.veryLightGreen,
  yellowBackground: palette.yellow,
  statsBackgroundGray: palette.backgroundGray,
  statHeaderComponentBackground: palette.mistyGray,
  courtMapBackground: palette.mistyGray,
  barGraphGreen: palette.brightGreen,
  barGraphOrange: palette.shadyOrange,
  barGraphRed: palette.juicyRed,
  transparentGrayBackground: palette.transparentGray,
  pieChartOrange: palette.grapefruitOrange,
  numberColorGray: palette.middleDarkGray,
  touchableContainerBackground: palette.ashGray,
  headerBackground: palette.mistyWhite,
  lineGray: palette.transparentVeryDarkGray,
  disabledButtonGray: palette.buttonsGray,
};
